{"name": "test_mp_login[13812345678-246810-1381234567118]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: '/Users/lq/python/test/2020-09/uiAutoTestHmtt/image//20200911165501_./imge/err.png.png'", "trace": "self = <scripts.test_01_mp_login.TestMpLogin object at 0x106106810>\nusername = '13812345678', code = 246810, expect = '1381234567118'\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        try:\n            # 断言\n>           assert expect == self.mp.page_get_nickname()\nE           AssertionError: assert '1381234567118' == '13812345678'\n\ntest_01_mp_login.py:31: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test_01_mp_login.TestMpLogin object at 0x106106810>\nusername = '13812345678', code = 246810, expect = '1381234567118'\n\n    @pytest.mark.parametrize(\"username, code, expect\", readyaml(\"mp_login.yml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        try:\n            # 断言\n            assert expect == self.mp.page_get_nickname()\n        except  Exception as e:\n            print(\"错误原因\",e)\n>           self.mp.base_get_img()\n\ntest_01_mp_login.py:34: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n../base/base.py:68: in base_get_img\n    self.__base_write_img(file_path)\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <page.page_mp_login.PageMpLogin object at 0x106131d90>\nfile_path = '/Users/lq/python/test/2020-09/uiAutoTestHmtt/image//20200911165501_./imge/err.png.png'\n\n    def __base_write_img(self, file_path):\n>       with open(file_path, \"r\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: '/Users/lq/python/test/2020-09/uiAutoTestHmtt/image//20200911165501_./imge/err.png.png'\n\n../base/base.py:71: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "code", "value": "246810"}, {"name": "expect", "value": "'1381234567118'"}], "start": 1599814499952, "stop": 1599814555519, "uuid": "c94b6cac-6306-4546-a2f4-baa153c37023", "historyId": "01ca993b08042689a3c1ac6e9760be33", "testCaseId": "0ef744100323d73770fc699b5f270c3a", "fullName": "scripts.test_01_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "promote.cache-dns.local"}, {"name": "thread", "value": "49612-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_01_mp_login"}]}